### ISSUE TITLE
Development workflow

### ISSUE THREAD

**Issue by zimmski** [bouk/staticfiles#12]
At the moment I have some additional features in my static.go file that was generated by "staticfiles". Everything is working fine and I am ready to do a PR but I have no idea how the development workflow of this repository works. Can you please document what needs to be installed and how it works together?

E.g. when I execute "make" nothing happens. When I remove ego.go and install "github.com/benbjohnson/ego" I receive an error that ego does not have the "-package" argument.

**Comment by bouk** [comment]
ah it seems ego was updated, I updated the package to support it. Should be fine now

**Comment by zimmski** [comment]
Could you please write a section in the README how to develop with this repository, e.g. what needs to be done to get a working environment (e.g. install ego) and what commands need to run to get the PR in general approved (e.g. I guess the example must be regenerated).
