### ISSUE TITLE
404 at bou.ke?

### ISSUE THREAD

**Issue by spieglt** [bouk/staticfiles#13]
Currently `go install github.com/bouk/staticfiles` fails because of line 1 in `staticfiles.go`, but you don't seem to be hosting the code at bou.ke/staticfiles any more. Should I just remove the import statement or is there a reason for it?

**Comment by bouk** [comment]
woops sorry I fixed it

**Comment by spieglt** [comment]
Hmm, it's still a 404 for me and the line is still there in `staticfiles.go`. How did you fix it?

**Comment by spieglt** [comment]
It seems to work perfectly when just removing that import comment, by the way. I'd rather use Github as the repo than a personal site. Needed a replacement for go-bindata and this fits the bill perfectly, thanks!

**Comment by spieglt** [comment]
Did you maybe forget to push the commit?

**Comment by bouk** [comment]
No, I fixed the site. https://bou.ke/staticfiles?go-get=1 Works now

**Comment by spieglt** [comment]
Ah, my bad, I was expecting to see something without the URL param. Thank you.

Another question: I guess there's no way to enumerate the files in the staticfiles.go archive, or query their names and paths? I'm writing a wrapper that will bundle an executable, DLLs, etc., and on launch, write them to `$tmp` and run the executable. I don't want to keep a static list of files as it may change without warning (depending on the Qt wrapper I'm using), so I want to be able to say "write every file in this archive to its proper location at this root." So maybe I ought to try https://github.com/GeertJohan/go.rice which has a `Walk` function.

**Comment by davidsteed** [comment]
This is not working again
