### ISSUE TITLE
Serve index.html

### ISSUE THREAD

**Issue by dimdin** [bouk/staticfiles#3]
Thank you @bouk for implementing this. 
Go built in file server serves index.html for directories.
Using the staticfiles server troubles me because I need to have in the URL "/index.html" instead of "/".
The following snippet solves the problem for the root directory.

``` go
func ServeHTTP(rw http.ResponseWriter, req *http.Request) {
    if req.URL.Path == "/" {
        req.URL.Path = "/index.html"
    } else if req.URL.Path == "/index.html" {
        rw.Header().Set("Location", "/")
        rw.WriteHeader(http.StatusMovedPermanently)
        return
    }
```

**Comment by bouk** [comment]
Hi! It seems to me you've already solved your problem, but I will accept a PR to add this feature

**Comment by zbindenren** [comment]
+1
